package main

// image_exec_path_test.go binds the build-time exec-path settings (ADR-19 U1,
// F-UNITPATH) to the Go source of truth, so a hand edit of either file cannot
// drift from internal/hostexec.
//
//   - the two systemd drop-ins the Dockerfile installs under
//     /usr/lib/systemd/system/<unit>.d/ must set exactly the reviewed directives,
//     and the PATH one must be hostexec.ChildPATH;
//   - containerd/config.toml must pin the shim, the runc binary and the three
//     directories containerd would otherwise execute from the Kairos-persistent
//     /opt, disable the plugins that look up a name the image does not ship, and
//     every path value must be an absolute path inside the read-only image.
//
// The TOML is read with an exact-line parser rather than a TOML library: the
// shipped file is generated by nothing and rewritten in one place only (the
// Dockerfile's sandbox_image sed), so a value that a real parser would accept but
// a human would misread -- a second assignment, a value spread over lines, a
// trailing comment -- is a finding, not something to normalize away. It mirrors
// parseSandboxImage in test/e2e/bundled_images.go and parse_sandbox_image in
// scripts/verify-bundle-refs.sh; scripts/verify-image-files.sh asserts the same
// lines against the SHIPPED image.

import (
	"fmt"
	"os"
	"path"
	"slices"
	"strings"
	"testing"

	"github.com/kairos-io/provider-kubernetes/internal/hostexec"
)

// Paths in the build context, relative to the repository root (this package).
const (
	containerdConfigSource      = "containerd/config.toml"
	containerdDropInSource      = "usr-lib-systemd/containerd.service.d/50-provider-kubernetes-exec-path.conf"
	kubeletDropInSource         = "usr-lib-systemd/kubelet.service.d/50-provider-kubernetes-exec-path.conf"
	containerdDropInImagePath   = "/usr/lib/systemd/system/containerd.service.d/50-provider-kubernetes-exec-path.conf"
	kubeletDropInImagePath      = "/usr/lib/systemd/system/kubelet.service.d/50-provider-kubernetes-exec-path.conf"
	imageVerifierBinDir         = "/usr/lib/containerd/image-verifier/bin"
	nriPluginPath               = "/usr/lib/nri/plugins"
	containerdShimPath          = "/usr/bin/containerd-shim-runc-v2"
	runcPath                    = "/usr/bin/runc"
	optPluginURI                = "io.containerd.internal.v1.opt"
	erofsDifferURI              = "io.containerd.differ.v1.erofs"
	erofsSnapshotterURI         = "io.containerd.snapshotter.v1.erofs"
	criRuncTable                = `plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc`
	criRuncOptionsTable         = criRuncTable + ".options"
	imageVerifierBindirTable    = `plugins."io.containerd.image-verifier.v1.bindir"`
	nriTable                    = `plugins."io.containerd.nri.v1.nri"`
	asciiSpace                  = " \t\n\v\f\r"
	dropInEnvironmentPATHPrefix = "Environment=PATH="
)

// readBuildFile reads a file from the build context, failing the test if it is
// missing: every path here is COPYed by the Dockerfile, so an absent file means
// the image ships without the setting.
func readBuildFile(t *testing.T, rel string) string {
	t.Helper()
	b, err := os.ReadFile(rel)
	if err != nil {
		t.Fatalf("read %s (the Dockerfile COPYs it into the image): %v", rel, err)
	}
	return string(b)
}

// systemdDirectives returns the section-qualified directives of a systemd unit
// file or drop-in, as "[<Section>] <Key>=<Value>" strings in file order.
// Comment lines ('#' or ';', which systemd both accept) and blank lines are
// ignored; a directive before any section header, an unterminated section header
// or a line without '=' is an error rather than something to skip.
func systemdDirectives(content string) ([]string, error) {
	if strings.IndexByte(content, 0) >= 0 {
		return nil, fmt.Errorf("drop-in contains a NUL byte")
	}
	section := ""
	var out []string
	for i, line := range strings.Split(content, "\n") {
		s := strings.Trim(line, asciiSpace)
		if s == "" || strings.HasPrefix(s, "#") || strings.HasPrefix(s, ";") {
			continue
		}
		if strings.HasPrefix(s, "[") {
			if !strings.HasSuffix(s, "]") {
				return nil, fmt.Errorf("line %d: unterminated section header %q", i+1, s)
			}
			section = s
			continue
		}
		if section == "" {
			return nil, fmt.Errorf("line %d: directive %q before any section header", i+1, s)
		}
		if !strings.Contains(s, "=") {
			return nil, fmt.Errorf("line %d: %q is not a Key=Value directive", i+1, s)
		}
		out = append(out, section+" "+s)
	}
	return out, nil
}

// TestExecPathDropInsSetExactlyTheReviewedDirectives is the ADR-19 U1
// source-of-truth binding: each shipped drop-in carries EXACTLY the directives
// below, in [Service], and the PATH one is hostexec.ChildPATH. "Exactly" matters as
// much as the values: a drop-in that also set, say, ExecStart or an EnvironmentFile
// would change the daemon in ways this file is not reviewed for, and an
// EnvironmentFile would outrank the PATH it is here to set.
//
// The two CONTAINERD_DISABLE_* variables are ADR-19 S19-18a: they stop containerd
// looking up igzip and unpigz by name, two of the three names it would otherwise
// search for and not find inside the image (mkfs.erofs, the third, is closed in
// containerd/config.toml). A name the image cannot satisfy is the only thing the
// appended /opt/nri/bin element could supply, so these are not optional.
func TestExecPathDropInsSetExactlyTheReviewedDirectives(t *testing.T) {
	pathDirective := "[Service] " + dropInEnvironmentPATHPrefix + hostexec.ChildPATH
	for _, tc := range []struct {
		source, imagePath string
		want              []string
	}{
		{containerdDropInSource, containerdDropInImagePath, []string{
			pathDirective,
			"[Service] Environment=CONTAINERD_DISABLE_IGZIP=1",
			"[Service] Environment=CONTAINERD_DISABLE_PIGZ=1",
		}},
		{kubeletDropInSource, kubeletDropInImagePath, []string{pathDirective}},
	} {
		t.Run(path.Base(path.Dir(tc.imagePath)), func(t *testing.T) {
			got, err := systemdDirectives(readBuildFile(t, tc.source))
			if err != nil {
				t.Fatalf("%s: %v", tc.source, err)
			}
			if !slices.Equal(got, tc.want) {
				t.Fatalf("%s sets %d directive(s)\n got: %q\nwant: %q\n(it is installed at %s)",
					tc.source, len(got), got, tc.want, tc.imagePath)
			}
			t.Logf("%s -> %s: %q", tc.source, tc.imagePath, got)
		})
	}
}

// TestChildPATHStaysInsideTheImage re-checks, from the drop-in's point of view,
// that the PATH the daemons hand to every helper they start holds only absolute
// directories inside the image. /usr/local is the Kairos persistent mount and /opt
// holds persistent state too, so either one in this value would give the daemons
// back the writable, upgrade-surviving lookup path U1 exists to remove.
func TestChildPATHStaysInsideTheImage(t *testing.T) {
	dirs := strings.Split(hostexec.ChildPATH, ":")
	if len(dirs) == 0 {
		t.Fatal("hostexec.ChildPATH is empty")
	}
	for _, dir := range dirs {
		switch {
		case !path.IsAbs(dir) || path.Clean(dir) != dir:
			t.Errorf("ChildPATH entry %q is not a clean absolute path", dir)
		case dir == "/usr/local" || strings.HasPrefix(dir, "/usr/local/"):
			t.Errorf("ChildPATH entry %q is under the persistent /usr/local", dir)
		case dir == "/opt" || strings.HasPrefix(dir, "/opt/"):
			t.Errorf("ChildPATH entry %q is under the persistent /opt", dir)
		}
	}
}

// tomlAssignment is one uncommented `key = value` line of a containerd config,
// qualified by the table it appears in ("" for the top level).
type tomlAssignment struct {
	Table string
	Key   string
	Value string // the raw text right of the first '=', trimmed
	Line  int    // 1-based
}

// parseTOMLAssignments splits a containerd version-2 config into its assignments
// using the same rules as parseSandboxImage (test/e2e/bundled_images.go) and
// parse_sandbox_image (scripts/verify-bundle-refs.sh): no NUL byte; lines trimmed
// of ASCII whitespace; blank and '#' lines ignored; a '[' line names the current
// table, without its '[' and ']' characters. A value containing '#' is refused
// rather than stripped: none of the keys asserted here may carry a trailing
// comment, and guessing where a comment starts inside a quoted value is exactly
// the ambiguity this parser exists to avoid.
func parseTOMLAssignments(doc string) ([]tomlAssignment, error) {
	if strings.IndexByte(doc, 0) >= 0 {
		return nil, fmt.Errorf("config.toml contains a NUL byte")
	}
	table := ""
	var out []tomlAssignment
	for i, line := range strings.Split(doc, "\n") {
		s := strings.Trim(line, asciiSpace)
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		if strings.HasPrefix(s, "[") {
			table = strings.Trim(strings.Trim(s, "[]"), asciiSpace)
			continue
		}
		key, value, ok := strings.Cut(s, "=")
		if !ok {
			return nil, fmt.Errorf("config.toml line %d: %q is not a key = value assignment", i+1, s)
		}
		value = strings.Trim(value, asciiSpace)
		if strings.Contains(value, "#") {
			return nil, fmt.Errorf("config.toml line %d: value %q contains '#'; a trailing comment is not supported here", i+1, value)
		}
		out = append(out, tomlAssignment{
			Table: table,
			Key:   strings.Trim(key, asciiSpace),
			Value: value,
			Line:  i + 1,
		})
	}
	return out, nil
}

// soleAssignment returns the value of key, requiring exactly one uncommented
// assignment of it in the whole document and that it sits in table. Both halves
// matter: a duplicate would make the effective value depend on containerd's merge
// order, and the same key in another table configures another plugin entirely.
func soleAssignment(all []tomlAssignment, table, key string) (string, error) {
	var found []tomlAssignment
	for _, a := range all {
		if a.Key == key {
			found = append(found, a)
		}
	}
	if len(found) != 1 {
		return "", fmt.Errorf("config.toml has %d assignments of %q, want exactly 1", len(found), key)
	}
	if found[0].Table != table {
		return "", fmt.Errorf("config.toml line %d: %q is in [%s], want [%s]", found[0].Line, key, found[0].Table, table)
	}
	return found[0].Value, nil
}

// TestContainerdConfigClosesPersistentExecPaths asserts the ADR-19 U1 containerd
// settings as exact values. Each one removes a root exec that would otherwise
// resolve through a Kairos-persistent directory:
//   - disabled_plugins: the `opt` plugin prepends /opt/containerd/bin to the
//     DAEMON's own PATH and /opt/containerd/lib to its LD_LIBRARY_PATH, which the
//     drop-in above cannot undo because it happens after exec;
//   - bin_dir: the image verifier runs binaries from it on every pull;
//   - plugin_path: containerd launches every executable in it at startup;
//   - runtime_path / BinaryName: the shim and runc are taken by absolute path
//     instead of being searched for.
//
// scripts/verify-image-files.sh asserts the same lines on the built image, so an
// edit that never reaches the image (or a build that rewrites the file) fails too.
func TestContainerdConfigClosesPersistentExecPaths(t *testing.T) {
	all, err := parseTOMLAssignments(readBuildFile(t, containerdConfigSource))
	if err != nil {
		t.Fatalf("%s: %v", containerdConfigSource, err)
	}

	for _, tc := range []struct{ name, table, key, want string }{
		{"opt and erofs plugins disabled", "", "disabled_plugins",
			`["` + optPluginURI + `", "` + erofsDifferURI + `", "` + erofsSnapshotterURI + `"]`},
		{"image-verifier bin_dir", imageVerifierBindirTable, "bin_dir", `"` + imageVerifierBinDir + `"`},
		{"NRI plugin_path", nriTable, "plugin_path", `"` + nriPluginPath + `"`},
		{"runc shim runtime_path", criRuncTable, "runtime_path", `"` + containerdShimPath + `"`},
		{"runc BinaryName", criRuncOptionsTable, "BinaryName", `"` + runcPath + `"`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := soleAssignment(all, tc.table, tc.key)
			if err != nil {
				t.Fatalf("%v", err)
			}
			if got != tc.want {
				t.Fatalf("%s = %s, want %s", tc.key, got, tc.want)
			}
			t.Logf("[%s] %s = %s", tc.table, tc.key, got)
		})
	}
}

// TestContainerdExecPathsAreImageOnly checks the property behind the exact values
// above, so a future change of one of those paths cannot quietly point back at a
// persistent directory: every path containerd is told to execute from, or execute,
// is absolute, clean, and neither under /opt nor under /usr/local.
func TestContainerdExecPathsAreImageOnly(t *testing.T) {
	for _, p := range []string{imageVerifierBinDir, nriPluginPath, containerdShimPath, runcPath} {
		switch {
		case !path.IsAbs(p) || path.Clean(p) != p:
			t.Errorf("%q is not a clean absolute path", p)
		case p == "/opt" || strings.HasPrefix(p, "/opt/"):
			t.Errorf("%q is under /opt, which Kairos keeps on the persistent partition", p)
		case p == "/usr/local" || strings.HasPrefix(p, "/usr/local/"):
			t.Errorf("%q is under the persistent /usr/local", p)
		}
	}
}
