// Package kubeadmconfig is a self-owned, minimal model of the kubeadm v1beta4
// configuration documents this provider emits, plus the kubelet v1beta1
// configuration. It intentionally does NOT import k8s.io/kubernetes (see ADR-1:
// importing those types drags the entire k8s.io staging graph and pins the build
// to a single minor). The kubeadm binary is the validator/executor; these types
// only need to render correct YAML for the fields we set.
//
// Fields are added as flows need them; this is deliberately a subset of the full
// v1beta4 schema, not a complete mirror.
package kubeadmconfig

// API group identifiers for the documents we emit.
const (
	KubeadmAPIVersion = "kubeadm.k8s.io/v1beta4"
	KubeletAPIVersion = "kubelet.config.k8s.io/v1beta1"

	KindClusterConfiguration = "ClusterConfiguration"
	KindInitConfiguration    = "InitConfiguration"
	KindJoinConfiguration    = "JoinConfiguration"
	KindKubeletConfiguration = "KubeletConfiguration"
)

// TypeMeta carries the apiVersion/kind every kubeadm document requires.
type TypeMeta struct {
	APIVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
}

// ClusterConfiguration is the cluster-wide kubeadm configuration.
type ClusterConfiguration struct {
	TypeMeta             `json:",inline"`
	KubernetesVersion    string     `json:"kubernetesVersion,omitempty"`
	ControlPlaneEndpoint string     `json:"controlPlaneEndpoint,omitempty"`
	ImageRepository      string     `json:"imageRepository,omitempty"`
	Networking           Networking `json:"networking,omitempty"`
	APIServer            APIServer  `json:"apiServer,omitempty"`
}

// Networking holds the cluster pod/service CIDRs and DNS domain.
type Networking struct {
	ServiceSubnet string `json:"serviceSubnet,omitempty"`
	PodSubnet     string `json:"podSubnet,omitempty"`
	DNSDomain     string `json:"dnsDomain,omitempty"`
}

// APIServer holds the subset of API server config we set.
type APIServer struct {
	CertSANs []string `json:"certSANs,omitempty"`
}

// InitConfiguration configures `kubeadm init` on the first control-plane node.
//
// BootstrapTokens and CertificateKey are credential-bearing and are populated by
// the credential layer (gated on ADR-2 / OQ-10), not by the foundation slice.
type InitConfiguration struct {
	TypeMeta         `json:",inline"`
	LocalAPIEndpoint APIEndpoint      `json:"localAPIEndpoint,omitempty"`
	NodeRegistration NodeRegistration `json:"nodeRegistration,omitempty"`
	BootstrapTokens  []BootstrapToken `json:"bootstrapTokens,omitempty"`
	CertificateKey   string           `json:"certificateKey,omitempty"`
}

// JoinConfiguration configures `kubeadm join` on additional nodes.
type JoinConfiguration struct {
	TypeMeta         `json:",inline"`
	Discovery        Discovery         `json:"discovery"`
	ControlPlane     *JoinControlPlane `json:"controlPlane,omitempty"`
	NodeRegistration NodeRegistration  `json:"nodeRegistration,omitempty"`
}

// APIEndpoint is a local API server endpoint.
type APIEndpoint struct {
	AdvertiseAddress string `json:"advertiseAddress,omitempty"`
	BindPort         int32  `json:"bindPort,omitempty"`
}

// NodeRegistration holds per-node registration settings.
type NodeRegistration struct {
	Name             string  `json:"name,omitempty"`
	CRISocket        string  `json:"criSocket,omitempty"`
	KubeletExtraArgs []Arg   `json:"kubeletExtraArgs,omitempty"`
	Taints           []Taint `json:"taints,omitempty"`
}

// Arg is a name/value argument. v1beta4 replaced the v1beta3 extraArgs map with a
// list of name/value pairs (duplicates allowed), which this models.
type Arg struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Taint is a node taint.
type Taint struct {
	Key    string `json:"key"`
	Value  string `json:"value,omitempty"`
	Effect string `json:"effect"`
}

// BootstrapToken is a kubeadm bootstrap token descriptor. Per ADR-2 the TTL is
// always bounded (never empty/"0") and the token value is CSPRNG-generated by the
// credential layer.
type BootstrapToken struct {
	Token  string   `json:"token"`
	TTL    string   `json:"ttl,omitempty"`
	Usages []string `json:"usages,omitempty"`
	Groups []string `json:"groups,omitempty"`
}

// Discovery configures how a joining node discovers and trusts the cluster.
type Discovery struct {
	BootstrapToken    *BootstrapTokenDiscovery `json:"bootstrapToken,omitempty"`
	File              *FileDiscovery           `json:"file,omitempty"`
	TLSBootstrapToken string                   `json:"tlsBootstrapToken,omitempty"`
}

// BootstrapTokenDiscovery is token-based discovery. Per ADR-2, CACertHashes MUST
// be set (CA pinning) and UnsafeSkipCAVerification MUST remain false.
type BootstrapTokenDiscovery struct {
	Token                    string   `json:"token"`
	APIServerEndpoint        string   `json:"apiServerEndpoint,omitempty"`
	CACertHashes             []string `json:"caCertHashes,omitempty"`
	UnsafeSkipCAVerification bool     `json:"unsafeSkipCAVerification"`
}

// FileDiscovery is discovery via a kubeconfig file (CA-pinned out of band).
type FileDiscovery struct {
	KubeConfigPath string `json:"kubeConfigPath"`
}

// JoinControlPlane configures joining as an additional control-plane node.
type JoinControlPlane struct {
	LocalAPIEndpoint APIEndpoint `json:"localAPIEndpoint,omitempty"`
	CertificateKey   string      `json:"certificateKey,omitempty"`
}

// NewClusterConfiguration returns a ClusterConfiguration with TypeMeta set.
func NewClusterConfiguration() ClusterConfiguration {
	return ClusterConfiguration{TypeMeta: TypeMeta{APIVersion: KubeadmAPIVersion, Kind: KindClusterConfiguration}}
}

// NewInitConfiguration returns an InitConfiguration with TypeMeta set.
func NewInitConfiguration() InitConfiguration {
	return InitConfiguration{TypeMeta: TypeMeta{APIVersion: KubeadmAPIVersion, Kind: KindInitConfiguration}}
}

// NewJoinConfiguration returns a JoinConfiguration with TypeMeta set.
func NewJoinConfiguration() JoinConfiguration {
	return JoinConfiguration{TypeMeta: TypeMeta{APIVersion: KubeadmAPIVersion, Kind: KindJoinConfiguration}}
}
